apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue # Kubernetes insists that ehy match the match labels.
    spec:
      containers:
      - name: queue
        image: richardchesterwood/k8s-fleetman-queue:release2

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-simulator
spec:
  selector:
    matchLabels:
      app: position-simulator
  template:
    metadata:
      labels:
        app: position-simulator # Kubernetes insists that ehy match the match labels.
    spec:
      containers:
      - name: position-simulator
        image: richardchesterwood/k8s-fleetman-position-simulator:release2
          # richardchesterwood/k8s-fleetman-position-tracker:release2
        env:
         - name: SPRING_PROFILES_ACTIVE
           value: production-microservice

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-tracker

spec:
  replicas: 2
  selector:
    matchLabels:
      app: position-tracker
  template:
    metadata:
      labels:
        app: position-tracker # Kubernetes insists that ehy match the match labels.
    spec:
      containers:
      - name: position-tracker
        image: richardchesterwood/k8s-fleetman-position-tracker:release2
        env:
         - name: SPRING_PROFILES_ACTIVE
           value: production-microservice


--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway # Kubernetes insists that ehy match the match labels.
    spec:
      containers:
      - name: api-gateway
        image: richardchesterwood/k8s-fleetman-api-gateway:release2
        env:
         - name: SPRING_PROFILES_ACTIVE
           value: production-microservice
--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp # Kubernetes insists that ehy match the match labels.
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release2  
        env:
         - name: SPRING_PROFILES_ACTIVE
           value: production-microservice

# richardchesterwood/k8s-fleetman-webapp-angular:release2           